version: '3'
services:
  database:
    image: mongo
    ports: 
      - 27017:27017
    command: mongod --logpath=/dev/null # --quiet
  api:
    build: .
    ports:
    - 8080:8080
    depends_on:
      - database
    links:
      - database
